# See also https://docs.github.com/en/actions/learn-github-actions/expressions
# See also https://github.com/marketplace/actions/setup-android-ndk

name: CI

on: [push, pull_request]

jobs:
  fbsd:
    runs-on: ubuntu-22.04
    name: A job to build sg3_utils on FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y curl
        run: |
          env
          freebsd-version
          pkg install -y autoconf
          pkg install -y automake
          pkg install -y autotools
          ./autogen.sh
          ./configure
          make CFLAGS="-Werror"
